# Generated by Django 5.2.8 on 2025-11-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_subscription_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='clinicadminprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='clinicadminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientfile',
            name='medical_record',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='primary_branch',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientfile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='receptionistprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='receptionistprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='work_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='website',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='order',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_branches',
            field=models.PositiveIntegerField(default=1, help_text='Макс. филиалов'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_patients',
            field=models.PositiveIntegerField(default=5000, help_text='Макс. пациентов'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_storage_gb',
            field=models.PositiveIntegerField(default=10, help_text='Макс. хранилище (ГБ)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_users',
            field=models.PositiveIntegerField(default=10, help_text='Макс. пользователей'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.plan'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ClinicAdminProfile',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientFile',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ReceptionistProfile',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
