# Generated by Django 5.2.8 on 2025-11-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limit_clinics',
            field=models.PositiveIntegerField(default=1, help_text='Макс. клиник для директора'),
        ),
    ]
