# Generated by Django 5.2.8 on 2025-11-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan_limit_clinics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='limit_storage_gb',
        ),
    ]
