# Generated by Django 5.2.8 on 2026-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_plan_limit_storage_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='working_hours',
            field=models.CharField(blank=True, default='', help_text='Пн-Пт 09:00 - 18:00', max_length=100),
        ),
    ]
