# Generated by Django 5.2.8 on 2026-01-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicadminprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='core.branch'),
        ),
    ]
