# Generated by Django 5.2.8 on 2026-01-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('archived', 'Архив')], default='active', max_length=20),
        ),
    ]
