# Generated by Django 5.2.8 on 2026-01-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_clinicdirectorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_history',
            field=models.TextField(blank=True),
        ),
    ]
